services:
  nest-telegram-sync:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ghcr.io/bsodium/nest-telegram-sync:latest
    container_name: nest-telegram-sync
    restart: unless-stopped
    env_file:
      - .env
